urls.py
# -*- coding: utf-8 -*-
#
#    shr.im * just an URL shortener
#    Copyright (C) 2009 Camille Bouiller <aftercem@gmail.com>
#    Copyright (C) 2009 Rémy Hubscher <natim@users.sf.net>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf import settings
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', 'shr.url.views.homepage'),
    (r'^login/?$', 'shr.oauthlogin.views.connection'),
    (r'^login/callback/?$', 'shr.oauthlogin.views.callback'),
    (r'^logout/?$', 'shr.oauthlogin.views.disconnect'),
    (r'^api/?$', 'shr.url.views.view_doc_api'),
    (r'^tools/?$', 'shr.url.views.view_tools'),
    (r'^contact/?$', 'shr.url.views.contact'),
    (r'^api/1.0/(?P<function>[-\w]+)$', 'shr.url.views.justAPIv1'),
    (r'^api/1.0/(?P<function>[-\w]+).(?P<format_output>[-\w]+)$', 'shr.url.views.justAPIv1'),
    (r'^ajax/(?P<function>[-\w]+)$', 'shr.url.views.ajax_pages'),
    (r'^timeline/?$', 'shr.url.views.urls_timeline'),
    (r'^popular/?$', 'shr.url.views.urls_popular'),
    (r'^s/(?P<alias>.*)/$', 'shr.url.views.view_fiche'),
    (r'^c/(?P<alias>.*)/$', 'shr.url.views.view_clics'),
    (r'^u/(?P<url>.*)/$', 'shr.url.views.view_user'),
    (r'^d/(?P<url>.*)/$', 'shr.url.views.view_domain'),
    (r'^del/(?P<alias>.*)/$', 'shr.url.views.delete'),
    (r'^admin/(.*)', admin.site.root),
    (r'^(http://.*)$', 'shr.url.views.prefixed_access'),
    (r'^(?P<alias>.*)/$', 'shr.url.views.redir'),
)

if settings.DEBUG:
	urlpatterns += patterns('',(r'^/site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
	(r'^upload/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	(r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),)

url/models.py
# -*- coding: utf-8 -*-
#
#    shr.im * just an URL shortener
#    Copyright (C) 2009 Camille Bouiller <aftercem@gmail.com>
#    Copyright (C) 2009 Rémy Hubscher <natim@users.sf.net>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django import forms
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from datetime import datetime
from shr.settings import MANAGERS

class Url(models.Model):
    auteur = models.ForeignKey(User, null=True, blank=True)
    url_src = models.URLField('source')
    url_min = models.CharField(max_length=20, null=True, blank=True, unique=True)
    domain = models.CharField(max_length=50)
    title = models.CharField(max_length=200, null=True, blank=True)
    description = models.CharField(max_length=300, null=True, blank=True, verbose_name='description')
    pub_date = models.DateTimeField(default=datetime.now, auto_now_add=True, verbose_name='created at')
    ip_post = models.IPAddressField(null=True, blank=True, verbose_name='IP', default='0.0.0.0')
    nb_clics = models.IntegerField(null=True, blank=True, default=0)
    is_private = models.BooleanField(default=0)
    country = models.ForeignKey('Country', null=True, blank=True)
    
    def __str__(self):
        return self.url_src
        
    def get_absolute_redir(self):
		return '/%s' % (self.url_min)
        
    def get_absolute_url(self):
		return '/s/%s/' % (self.url_min)
        
class UrlForm(forms.ModelForm):
    url_min = forms.CharField(max_length=20, required=False)
    is_private = forms.BooleanField(required=False)
    
    class Meta:
        model = Url
        fields = ['url_src', 'url_min', 'is_private']
        
    def clean_url_src(self):
        source_url = self.cleaned_data['url_src']
        if not source_url.startswith('http://') and not source_url.startswith('https://'):
            return 'http://%s' % (source_url)
        return source_url
 
    def clean_url_min(self):
        alias_url = self.cleaned_data['url_min']
        try:
            Url.objects.get(url_min__exact=alias_url)
            raise forms.ValidationError('This alias is already token!')
        except Url.DoesNotExist:
            return alias_url

        raise forms.ValidationError('This alias is already token!')
        
class EditForm(forms.ModelForm):
    is_private = forms.BooleanField(required=False)
    
    class Meta:
        model = Url
        fields = ['url_src', 'is_private']
        
    def clean_url_src(self):
        source_url = self.cleaned_data['url_src']
        if not source_url.startswith('http://') and not source_url.startswith('https://'):
            return 'http://%s' % (source_url)
        return source_url
		
class API(models.Model):
    LIST_ETAT = (
		(2, 'Actif'),
		(1, 'En attente'),
		(0, 'Désactivé'),
	)
    
    auteur = models.ForeignKey(User)
    pseudo = models.CharField(max_length=30)
    cle = models.CharField(max_length=30, verbose_name='Clé')
    etat = models.IntegerField(max_length=1, choices=LIST_ETAT, default=1)
    nb_rqt = models.IntegerField(null=True, blank=True, default=0, verbose_name='Nombre de requêtes')
    last_ip = models.IPAddressField(null=False, blank=False, verbose_name='IP', default='0.0.0.0')
    date_propose = models.DateTimeField(verbose_name='Date de soumission', null=True, blank=True)
    last_date = models.DateTimeField(verbose_name='Dernière activité', null=True, blank=True)
    
    class Meta:
        verbose_name_plural = 'API'
        
class Country(models.Model):
    name = models.CharField(max_length=50)
    int = models.CharField(max_length=50)
    nb_clics = models.IntegerField(null=True, blank=True, default=0)
    nb_links = models.IntegerField(null=True, blank=True, default=0)
    
    def __str__(self):
        return self.name
    
class Geoloc(models.Model):
    link = models.ForeignKey(Url)
    country = models.ForeignKey(Country)
    nb_clics = models.IntegerField(null=True, blank=True, default=0)
    
class Clic(models.Model):
    url = models.ForeignKey(Url)
    pub_date = models.DateTimeField(default=datetime.now, auto_now_add=True, verbose_name='created at')
    ip_post = models.IPAddressField(null=True, blank=True, verbose_name='IP', default='0.0.0.0')
    referer = models.URLField(null=True, blank=True)
    country = models.ForeignKey(Country, null=True, blank=True)
    
class ContactForm(forms.Form):
    pseudo = forms.CharField(label='Name', required=False)
    mail = forms.EmailField(label='Email')
    objet  = forms.CharField(label='Topic', required=False)
    message = forms.CharField(label='Content',widget=forms.Textarea)

    def send(self, mails=[]):
        if self.is_valid():
            if not mails:
                mails = [a[1] for a in MANAGERS]
            # Codage de l'envoi
            subject = u'%s' % (self.cleaned_data['objet'])
            msg = EmailMessage(subject, self.cleaned_data['message'], self.cleaned_data['mail'], mails)
            try:
                msg.send()
            except:
                return False

            return True

        return False
        

templates/api.html
{% extends "base.html" %}
{% block title %}API Documentation{% endblock %}
{% block content %}

<div id="header">
    <div class="size_content">
        <a href="/" title="Just an url shortener"><img src="/site_media/img/logo.jpg" id="logo" alt="Just an url shortener" /></a>
        <div class="right_head">
            <h1>API</h1>
        </div>
        <hr class="clearehr" />
    </div>
</div>

<div class="size_content" id="contenu">
    {% if num_msg %}
        {% ifequal num_msg 50 %}<div id="msg" class="success">You have now an API account.</div>{% endifequal %}
        {% ifequal num_msg 51 %}<div id="msg" class="success">Your API key has been changed.</div>{% endifequal %}
        {% ifequal num_msg 52 %}<div id="msg" class="success">Now you no longer have API account.</div>{% endifequal %}
    {% endif %}
    
    <h2>Api account</h2>

    <img src="/site_media/img/icon_api2.png" alt="" style="float: left; margin-right: 15px;" />
    <p>This API allows you to use all the shr.im features on your site. Post a link, edit or delete it, through the detailed information of a link...</p>
    <p>All proposed functions <strong>Requires Authentication</strong> (just register with his Twitter account, and request an API key).</p>
    <p>Sample Query API : <span class="pcode clink">{{ domain_api }}popular.json?<strong>api_user</strong>=your_nick&<strong>api_key</strong>=your_key</span><br />
    <span style="font-size: 0.85em;">Obviously you need to replace api_user / api_key to your username / key for this to work.</span></p>
    <br />
    <div class="send_request">
    
    {% if request.user.is_authenticated %}
        {% if account_api %}
        <ul>
            <li><strong>Your username :</strong> {{ account_api.pseudo }}</li>
            <li><strong>Your key :</strong> {{ account_api.cle }}</li>
            <li><a href="/api/?act=delete&key={{ account_api.cle }}" class="cssbutton" style="float: right;" onclick="if(!confirm('	Are you sure you want to remove your API account?')){return false}"><img src="/site_media/img/close.png" alt="" /> Delete your API account</a> <a href="/api/?act=reset&key={{ account_api.cle }}" class="cssbutton"><img src="/site_media/img/reset.png" alt="" /> Reset my key</a><hr class="clearehr" /></li>
        </ul>
        {% else %}
        <form action="/api/?send_request=1" method="post" style="text-align: center;">
            <p><strong>You don't have an API account yet.</strong></p>
            <p style="margin-bottom: 5px;"><label><input name="accept_tos" id="accept_tos" type="checkbox" /> Accept the <a href="/tos/">Terms of Service</a></label></p>
            <p style="width: 150px; margin: 0 auto;"><input name="submit" type="submit" value="Request Account API" class="cssbutton" style="width: 150px; text-align: center;" /></p>
            <hr class="clearehr" />
        </form>
        {% endif %}
    {% else %}
        <p style="text-align: center;">
            You need to <a href="/login/">login</a> with your Twitter account for request a API account.
        </p>
    {% endif %}
    </div>
    
    <h2>Documentation</h2>
    <ul id="chap">
        <li><a href="#fct_public_timeline">public_timeline</a></li>
        <li><a href="#fct_home_timeline">home_timeline</a></li>
        <li><a href="#fct_popular">popular</a></li>
        <li><a href="#fct_view">view</a></li>
        <!-- <li><a href="#fct_view_url">view_url</a></li> -->
        <li><a href="#fct_by_domain">by_domain</a></li>
        <li><a href="#fct_by_user">by_user</a></li>
        <li><a href="#fct_post">post</a></li>
        <li><a href="#fct_edit">edit</a></li>
        <li><a href="#fct_delete">delete</a></li>
    </ul>
    
    <div class="row_doc">
        <h3 id="fct_public_timeline">public_timeline  <span class="tdesc">Get last links posted</span></h3>
        <ul class="ddata">
            <li>URL : <span class="pcode">{{ domain_api }}public_timeline.<em>format</em></span></li>
            <li>Formats : xml, json</li>
            <li>HTTP Method : GET</li>
            <li>Requires Authentication : yes</li>
            <li>Parameters : <ul>
                <li>None</li>
            </ul></li>
        </ul>
    </div>
    
    <div class="row_doc">
        <h3 id="fct_home_timeline">home_timeline <span class="tdesc">Get your links</span></h3>
        <ul class="ddata">
            <li>URL : <span class="pcode">{{ domain_api }}home_timeline.<em>format</em></span></li>
            <li>Formats : xml, json</li>
            <li>HTTP Method : GET</li>
            <li>Requires Authentication : yes</li>
            <li>Parameters : <ul>
                <li>None</li>
            </ul></li>
        </ul>
    </div>
    
    <div class="row_doc">
        <h3 id="fct_popular">popular <span class="tdesc">Top links right now</span></h3>
        <ul class="ddata">
            <li>URL : <span class="pcode">{{ domain_api }}popular.<em>format</em></span></li>
            <li>Formats : xml, json</li>
            <li>HTTP Method : GET</li>
            <li>Requires Authentication : yes</li>
            <li>Parameters : <ul>
                <li>None</li>
            </ul></li>
        </ul>
    </div>
    
    <div class="row_doc">
        <h3 id="fct_view">view <span class="tdesc">Detailed information of a link</span></h3>
        <ul class="ddata">
            <li>URL : <span class="pcode">{{ domain_api }}view.<em>format</em></span></li>
            <li>Formats : xml, json</li>
            <li>HTTP Method : GET</li>
            <li>Requires Authentication : yes</li>
            <li>Parameters : <ul>
                <li>alias (required) : unique identifier of the link (i.e : "test20" for shr.im/apistats)</li>
            </ul></li>
        </ul>
    </div>
    
    <div class="row_doc">
        <h3 id="fct_by_domain">by_domain <span class="tdesc">Display links by domain</span></h3>
        <ul class="ddata">
            <li>URL : <span class="pcode">{{ domain_api }}by_domain.<em>format</em></span></li>
            <li>Formats : xml, json</li>
            <li>HTTP Method : GET</li>
            <li>Requires Authentication : yes</li>
            <li>Parameters : <ul>
                <li>domain (required) : URL of domain (i.e : digg.com, news.cnet.com)</li>
            </ul></li>
        </ul>
    </div>
    
    <div class="row_doc">
        <h3 id="fct_by_user">by_user <span class="tdesc">Display links by user</span></h3>
        <ul class="ddata">
            <li>URL : <span class="pcode">{{ domain_api }}by_user.<em>format</em></span></li>
            <li>Formats : xml, json</li>
            <li>HTTP Method : GET</li>
            <li>Requires Authentication : yes</li>
            <li>Parameters : <ul>
                <li>user (required) : username of user (i.e : shr_im, nephthys)</li>
            </ul></li>
        </ul>
    </div>
    
    <div class="row_doc">
        <h3 id="fct_post">post <span class="tdesc">Post a new link</span></h3>
        <ul class="ddata">
            <li>URL : <span class="pcode">{{ domain_api }}post.<em>format</em></span></li>
            <li>Formats : xml, json, text</li>
            <li>HTTP Method : GET</li>
            <li>Requires Authentication : yes</li>
            <li>Parameters : <ul>
                <li>url_src (required) : URL of the link</li>
                <li>url_min (optional) : unique identifier of the link</li>
                <li>is_private (optional) : public (0, default) or private (1)</li>
            </ul></li>
        </ul>
    </div>
    
    <div class="row_doc">
        <h3 id="fct_edit">edit <span class="tdesc">Edit a link</span></h3>
        <ul class="ddata">
            <li>URL : <span class="pcode">{{ domain_api }}edit.<em>format</em></span></li>
            <li>Formats : xml, json</li>
            <li>HTTP Method : GET</li>
            <li>Requires Authentication : yes</li>
            <li>Parameters : <ul>
                <li>url_min (required) : identifier of the link to edit</li>
                <li>url_src (required) : new URL of the link</li>
            </ul></li>
        </ul>
    </div>
    
    <div class="row_doc">
        <h3 id="fct_delete">delete <span class="tdesc">Delete a link</span></h3>
        <ul class="ddata">
            <li>URL : <span class="pcode">{{ domain_api }}delete.<em>format</em></span></li>
            <li>Formats : xml, json</li>
            <li>HTTP Method : GET</li>
            <li>Requires Authentication : yes</li>
            <li>Parameters : <ul>
                <li>url_min (required) : identifier of the link to delete</li>
            </ul></li>
        </ul>
    </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
<head>
	<title>{% block title %}shr.im &bull; just an url shortener{% endblock %}</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-language" content="en" />
	<link rel="stylesheet" type="text/css" href="/site_media/style.css" media="screen" />
    <link rel="shortcut icon" type="image/x-icon" href="/site_media/img/favicon.ico" />
</head>

<div id="heads">
    <div class="size_content">
    <div class="float_right">
    {% if request.user.is_authenticated %}
        {% if request.user.get_profile.avatar_url %}
        <img src="{{ request.user.get_profile.avatar_url }}" alt="Your avatar" style="width: 22px;" class="style_avatar" />&nbsp;
        {% endif %}
        Hello {{ request.user.username }} (<a href="/logout/">Logout</a>)
    {% else %}
        <a href="/login/"><img src="/site_media/login_twitter.png" alt="Sign in with Twitter" /></a>
    {% endif %}
    </div>
    <ul id="menu">
        <li><a href="/">Home</a></li>
        <li><a href="/timeline/">Timeline</a></li>
        <li><a href="/popular/">Popular</a></li>
        <li><a href="/tools/">Tools</a></li>
        {% if request.user.is_authenticated %}{% if request.user.is_superuser %}<li><a href="/admin/"><strong>Admin</strong></a></li>{% endif %}{% endif %}
    </ul>
    </div>
</div>

{% block content %}{% endblock %}

<div id="footer">
    <a href="/">Home</a> &nbsp;&bull;&nbsp;
    <a href="/contact/">Contact</a> &nbsp;&bull;&nbsp;
    <a href="http://blog.shr.im">Blog</a> &nbsp;&bull;&nbsp;
    <a href="/api/">API</a> &nbsp;&bull;&nbsp;
    <a href="http://shr.im/twitter/">Twitter</a> &nbsp;&bull;&nbsp;
    <a href="http://shrim.uservoice.com/pages/31810-general">Feedback</a> &nbsp;&nbsp;&nbsp;
    by @<a href="http://shr.im/twitr">nephthys</a>
</div>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<script type="text/javascript" src="/site_media/effects.js"></script>
<script type="text/javascript" src="//static.woopra.com/js/woopra.js"></script>
<script type="text/javascript">var uservoiceJsHost = ("https:" == document.location.protocol) ? "https://uservoice.com" : "http://cdn.uservoice.com"; document.write(unescape("%3Cscript src='" + uservoiceJsHost + "/javascripts/widgets/tab.js' type='text/javascript'%3E%3C/script%3E"))</script>
<script type="text/javascript">UserVoice.Tab.show({ key: 'shrim', host: 'shrim.uservoice.com', forum: '31810', alignment: 'right', background_color:'#92c800', text_color: 'white', hover_color: '#353535', lang: 'en'})</script>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-11463997-1");
pageTracker._trackPageview();
} catch(err) {}</script>

<body>
</body>
</html>

templates/clean_status.html
{% extends "base.html" %}
{% block title %}URL's Title and Description cleaner{% endblock %}
{% block content %}

<div id="header">
    <div class="size_content">
        <a href="/" title="Just an url shortener"><img src="/site_media/img/logo.jpg" id="logo" alt="Just an url shortener" /></a>
        <div class="right_head">
            <h1>URL's Title and Description cleaner</h1>
        </div>
        <hr class="clearehr" />
    </div>
</div>

<div class="size_content" id="contenu">
    <h2>Cleaner log</h2>

    <ul>
      {% for item in urls %}
      <li><a href="{{ item.url.get_absolute_redir }}">{{ item.url.title }}</a> - {% if item.fixed %}<span style="color: green;">[DONE]</span>{% else %}<span style="color: red;">[FAILED]</span>{% endif %}</li>
      {% endfor %}
    </ul>

</div>

{% endblock %}

templates/post.html
<h1>shr.im - coming soon!</h1>

templates/post_old.html
{% extends "base.html" %}
{% block content %}


<!-- post a new link -->

<form id="new_link" action="./" method="post">

<div id="header">
    <div class="size_content">
        <a href="/" title="Just an url shortener"><img src="/site_media/img/logo.jpg" id="logo" alt="Just an url shortener" /></a>
        <div class="right_head">
            <input id="id_url_src" type="text" name="url_src" maxlength="200" value="Your long URL" onclick="if(this.value=='Your long URL') this.value='';" />
        </div>
        <hr class="clearehr" />
    </div>
</div>
<div class="size_content">
    <div class="right_head2">
        <div class="float_right">
            <span id="my_loader_place"></span>
            <input type="submit" name="submit" id="submit_butt" value="Share!" />
        </div>
        
        <div class="more_options_space">
        
        <span id="more_options"><a href="#" class="link_plus_options show_side">More options</a></span>
        <div style="display: none;" id="more_options_hide">
            <a href="#" class="link_plus_options hide_side">Hide options</a>
            <table class="forms">
            <tr><th><label for="id_url_min">Alias : </label></th><td><input id="id_url_min" type="text" name="url_min" maxlength="20" /></td></tr>
            {% if request.user.is_authenticated %}<tr><th><label for="id_is_private">Is private ?</label></th><td><input id="id_is_private" type="checkbox" name="is_private" /></td></tr>{% endif %}
            </table>
        </div>
        
        </div>
        <hr class="clearehr" />
    </div>
</div>

</form>

<div class="size_content">
<div id="my_content_newlinks"></div>
{% comment %}
0* : Connexion
1* : Ajout URL
2* : Conversation avec twitter
3* : Suppression URL
5* : Messages API
6* : Formulaire de contact
{% endcomment %}
{% if num_msg %}
    {% ifequal num_msg 1 %}<div id="msg" class="error">Oops, fatal error!</div>{% endifequal %}
    {% ifequal num_msg 2 %}<div id="msg" class="success">You are now logged!</div>{% endifequal %}
    {% ifequal num_msg 3 %}<div id="msg" class="success">You have been disconnected.</div>{% endifequal %}
    {% ifequal num_msg 10 %}<div id="msg" class="error">Long URL is required.</div>{% endifequal %}
    {% ifequal num_msg 11 %}<div id="msg" class="error">This link does not exist.</div>{% endifequal %}
    {% ifequal num_msg 12 %}<div id="msg" class="error">Long URL is invalid.</div>{% endifequal %}
    {% ifequal num_msg 30 %}<div id="msg" class="success">Your URL has been deleted.</div>{% endifequal %}
{% endif %}

{% for field in form %}
    {% if field.errors %}
    <strong>{{ field.label }}</strong> : {% for error in field.errors %} {{ error }} {% endfor %}<br />
    {% endif %}
{% endfor %}

{% if request.user.is_authenticated %}
<h2><a href="{{ request.user.get_profile.get_absolute_url }}">Your last links</a></h2>

{% load appname_tags %}

{% if list_urls %}
{% for url in list_urls %}
<div class="{% cycle 'row_tr1' 'row_tr2' %}">
<table class="row_url">
<tr id="row_tr_{{ url.id }}">
    <td class="td_date">{{ url.pub_date|date_diff }}</td>
    <td class="td_title is_author_link">
        <h3>{% if url.is_private %}<img src="/site_media/img/lock.png" alt="Private URL" /> {% endif %}<span id="title_edit_link_{{ url.id }}">{{ url.title }}</span></h3>
        <div class="details_url" id="url_edit_link_{{ url.id }}">
            <a href="{{ url.get_absolute_redir }}" id="src_edit_link_{{ url.id }}">{{ url.url_src }}</a>
            <span style="display: none;" class="hide_opt_focus"> 
                &nbsp;&nbsp; <a href="#" class="show_form_edit_link" id="edit_link_{{ url.id }}" title="edit this link">edit</a> &nbsp;
                <a href="#" class="show_form_delete_link" id="delete_link_{{ url.id }}" title="delete this link">delete</a>
            </span>
        </div>
        <div class="edit_form" id="form_edit_link_{{ url.id }}" style="display: none;"> 
            <form action="/edit/{{ url.url_min }}" method="post">
                <p><input name="new_url" id="url_submit_form_{{ url.id }}" type="text" value="{{ url.url_src }}" class="input_new_url" /><input name="idl" id="idl_submit_form_{{ url.id }}"type="hidden" value="{{ url.id }}" />
                <span id="preload_{{ url.id }}"> </span>
                <span id="edittext_{{ url.id }}"> <input name="submit" type="submit" class="small_submit submit_edit_form" id="submit_form_{{ url.id }}" value="Edit!" /> or <a href="#" class="show_form_edit_link" id="edit_link_{{ url.id }}">Cancel</a></span></p>
            </form>
        </div>
    </td>
    <td class="td_clics"><a href="{{ url.get_absolute_url }}">{{ url.nb_clics }} clic{% ifnotequal url.nb_clics 0 %}{% ifnotequal url.nb_clics 1 %}s{% endifnotequal %}{% endifnotequal %}</a></td>
    <td class="td_stats"><a href="{{ url.get_absolute_url }}"><img src="/site_media/img/more_stats.png" alt="" /> Stats</a></td>
</tr>
</table>
</div>
{% endfor %}

{% if show_page %}
<ul class="list_pages"><li class="int"><span>Page(s) :</span></li>
{% for current_page in list_page %}
	{% ifequal current_page page %}
	<li class="current"><span>{{ current_page }}</span></li>
	{% else %}
	{% ifequal current_page separateur %}
	<li class="sep"><span>{{ separateur }}</span></li>
	{% else %}
	<li class="pg"><a href="?p={{ current_page }}">{{ current_page }}</a></li>
	{% endifequal %}
	{% endifequal %}
{% endfor %}</ul>
{% endif %}
{% endif %}

{% else %}

<h2>Why register?</h2>
<div id="take_a_tour" class="list_graphs">
<dl>
    <dt><img src="/site_media/img/icon_manage2.png" alt="" /> Manage your links</dt>
    <dd>Access all your links and their statistics in real time.</dd>
</dl>
<dl>
    <dt><img src="/site_media/img/icon_twitter.png" alt="" /> Fast and easy</dt>
    <dd>Sign in with your Twitter account, it takes a few seconds and requires no password.</dd>
</dl>
<dl>
    <dt><img src="/site_media/img/icon_api.png" alt="" /> API access</dt>
    <dd>Use features and data of shr.im on your site or application.</dd>
</dl>
<hr class="clearehr" />
<p style="margin-bottom: 0; margin-left: 1%; font-weight: bold;"><a href="/login/">Sign in or sign up now</a></p>
</div>

{% endif %}

</div>

{% endblock %}